# Test the netcdf handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

besstandalone_start "cedar/mfp920504a.info.bescmd"
compare_stdout "cedar/mfp920504a.info.bescmd.baseline" "mfp920504a info" 0

